#!/bin/bash

echo ""
echo "============================================"
echo "  Setup complete! Manual steps remaining:"
echo "============================================"
echo ""
echo "[ ] SSH key:"
echo "      ssh-keygen -t ed25519 -C \"your@email.com\""
echo "      cat ~/.ssh/id_ed25519.pub  # add to GitHub"
echo ""
echo "[ ] Git credentials:"
echo "      Edit ~/.config/git/config with your name and email"
echo ""
echo "[ ] Sign in:"
echo "      App Store, iCloud"
echo ""
echo "[ ] Install Xcode from App Store (if iOS/macOS dev needed)"
echo ""
echo "[ ] Activate licenses for paid apps (e.g. Raycast Pro)"
echo ""
echo "[ ] Reboot to apply all settings cleanly"
echo ""
